### ISSUE TITLE
consistency of root-sudo in README

### ISSUE THREAD

**Issue by dreamerchris** [coolshou/rtl8821cu#1]
I see in your readme that you are not 100% consistent about what is run as root/sudo

for example the insmod 8821cu.k and the apt install  commands did not run without sudo it said no permission or something like that

either make a note that all commands should be run as sudo/root or have your instruction include sudo where its needed!

all in all, thank you for your driver it really is great! works like a charm!!!!!

**Comment by coolshou** [comment]
close #80fdfe4dfa1fda9a2227ea702959fe826ca84766
